### ISSUE TITLE
rtx python plugin with .venv virtualenv unable to find dynamic library.

### ISSUE THREAD

**Issue by yssource** [jdx/rtx#530]
```
[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
python = 'https://github.com/jdxcode/rtx-python'

[tools]
python = { version = "latest", virtualenv = "{{env.HOME}}/.cache/venv" }

```
* rtx pip install conan

```
➜ /home/jimmy/.cache/venv/bin/conan --version
Traceback (most recent call last):
  File "/home/jimmy/.cache/venv/bin/conan", line 5, in <module>
    from conans.conan import run
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conans/conan.py", line 3, in <module>
    from conan.cli.cli import main
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/cli/cli.py", line 13, in <module>
    from conan.api.conan_api import ConanAPI
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/api/conan_api.py", line 3, in <module>
    from conan.api.subapi.cache import CacheAPI
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/api/subapi/cache.py", line 3, in <module>
    from conan.internal.conan_app import ConanApp
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/internal/conan_app.py", line 3, in <module>
    from conans.client.cache.cache import ClientCache
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conans/client/cache/cache.py", line 9, in <module>
    from conan.internal.cache.cache import DataCache, RecipeLayout, PackageLayout
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 8, in <module>
    from conan.internal.cache.db.cache_database import CacheDatabase
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/internal/cache/db/cache_database.py", line 1, in <module>
    from conan.internal.cache.db.packages_table import PackagesDBTable
  File "/home/jimmy/.cache/venv/lib/python3.11/site-packages/conan/internal/cache/db/packages_table.py", line 1, in <module>
    import sqlite3
  File "/home/jimmy/.local/share/rtx/installs/python/3.11.3/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/jimmy/.local/share/rtx/installs/python/3.11.3/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

* However, The system default conan works ok.
```
/usr/bin/conan --version
Conan version 2.0.4
```

**Comment by yssource** [comment]
It's a problem caused that it is depending a outdated `sqlite3` library when compiling the python source. 

https://github.com/pyenv/pyenv/issues/2625#issuecomment-1773719291
