### ISSUE TITLE
Python Installs Are Missing Modules

### ISSUE THREAD

**Issue by KerickHowlett** [jdx/rtx#823]
**Describe the bug**
Using a clean install of `rtx` via Cargo on my Linux machine (Pop!_OS), and when I installed the latest version of Python (3.11), I received all these warning regarding missing modules _(as seen in the snippet below)_.

```bash
Downloading Python-3.11.4.tar.xz...
-> https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kingofheroes/.local/share/rtx/installs/python/3.11.4/lib/python3.11/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.11.4 to /home/kingofheroes/.local/share/rtx/installs/python/3.11.4
rtx python@3.11.4 
```

I received a near identical output when I installed Python 3.10.

Admittedly, I'm rather new at Python, so I don't know if this is usual, but I get paranoid whenever I see errors/warnings like this; however, I didn't receive these sort of warnings when installing Python 3.9 on my MacBook Pro that I use for work. (I had installed `rtx` using Homebrew on that computer.)

**To Reproduce**
All you have to do is enter the following command:
```bash
rtx install python@latest

# Or this command

rtx install python@3.10
```

**Expected behavior**

**`rtx doctor` output**

```                                                                                                                        ─╯
rtx version:
  2023.8.2 linux-x64 (2023-08-19)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Sat, 19 Aug 2023 18:59:12 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03)
  Profile: release

shell:
  fish
  fish, version 3.6.1

rtx data directory:
  /home/kingofheroes/.local/share/rtx

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/kingofheroes/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  node@latest, python@latest

No problems found
```

**Comment by KerickHowlett** [comment]
> @KerickHowlett rtx use pyenv(python-build as a pyenv plugin) to install python under the hood,  you need to install dependencies first for building from sources before you run `rtx install python`
> 
> https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Oh! That makes sense! On my work computer, I had Pyenv installed before switching over to `rtx`. 😅

Anyway, thanks for the response! I'll try this out soon, and I'll let you know how it goes.

**Comment by KerickHowlett** [comment]
I just realized I forgot to provide an actual update on this. lol

Anyway, it worked, so I'm gonna go ahead and close this issue!

Thanks again for the fast assistance! :)
